# -*- coding: utf-8 -*-
"""NGram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yA4y1-035S4D4G9NnGWzUm-gBjYHs4co
"""

!wget https://raw.githubusercontent.com/karpathy/makemore/refs/heads/master/names.txt

words = open('names.txt', 'r').read().splitlines()

import torch

N = torch.zeros((27, 27), dtype = torch.int32)

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}

for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    N[ix1, ix2] += 1

P = N.float()
P = P / P.sum(1, keepdim= True)
g = torch.Generator().manual_seed(2147483647)
ix = 0
for i in range(50):
  out = []
  while True:
    p = P[ix]
    ix = torch.multinomial(p, num_samples = 1, replacement = True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))

"""Trigram model"""

N = torch.zeros((27, 27, 27), dtype = torch.int)
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    N[ix1, ix2, ix3] += 1

P = (N + 1).float()
P = P / P.sum(2, keepdim=True)

g = torch.Generator().manual_seed(2147483647)

P = (N+1).float()
P = P / P.sum(2, keepdim= True)
g = torch.Generator().manual_seed(2147483647)


for i in range(50):
  out = []
  ix1 = 0
  ix2 = 0
  while True:
    p = P[ix1, ix2]
    ix3 = torch.multinomial(p, num_samples = 1, replacement = True, generator=g).item()
    out.append(itos[ix3])
    ix1 = ix2
    ix2 = ix3
    if ix3 == 0:
      break
  print(''.join(out))

